# cspell.yaml

version: "0.2"
language: "en"

dictionaryDefinitions:
  - name: terms-primary
    path: ./.cspell.terms.txt
  - name: misc
    path: ./.cspell.misc.txt
dictionaries:
  - terms-primary
  - misc
ignorePaths:
  - ./.cspell.terms.txt
  - ./.cspell.misc.txt
