# https://taskfile.dev

version: "3"

tasks:
  default:
    cmds:
      - task --list-all
  build:
    internal: true
    summary: |
      Build complete webpage for production.

      The build output paths are configured in `./svelte.config.js`
      and they assume a _speific directory structure_ outside of this repository.
    aliases: [b]
    cmds:
      - npm run build
      - task: link
  dev:
    summary: |
      Run the page in development mode.
      This mode does not require any prerequisites.
    aliases: [d]
    cmd: npm run dev
  lint:
    cmds:
      - task: lint:spellcheck
  lint:spellcheck:
    summary: Runs cspell linter with `./.cspell.yaml` tree of configurations
    cmd: cspell ./src/lib/rebis_theory.mdx
  link:
    internal: true
    cmds:
      # with each production build chunk names are different,
      # so we will copy entire html with svelte bootstrap scripts
      # to hugo's domain,
      # and, as paths are relative,
      # it will be no issue for hugo-based initial route resolution
      - cp ./../../static/entries/rebis-theory/index.html ./../../layouts/entries/single.html
      # - cp static/entries/rebis-theory/index.html layouts/entries/single.html
